//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy_V
    {
        public string Expr1 { get; set; }
        public string MaSV { get; set; }
        public int MaLopTC { get; set; }
        public int Expr2 { get; set; }
    }
}
