//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DongHocPhi
    {
        [Required(ErrorMessage = "Mã sinh viên không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã sinh viên")]
        public string MaSV { get; set; }

        [Required(ErrorMessage = "ID không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "ID Học phí")]
        public string IDHocPhi { get; set; }

        [Required(ErrorMessage = "Ngày không được trống")]
        [Display(Name = "Ngày")]
        public System.DateTime Ngay { get; set; }
        public int SoTien { get; set; }
        public string NienKhoa { get; set; }

        public virtual HocPhiTheoDangKy HocPhiTheoDangKy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
