//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongHocPhi
    {
        public string MaSV { get; set; }
        public string IDHocPhi { get; set; }
        public System.DateTime Ngay { get; set; }
        public int SoTien { get; set; }
        public string NienKhoa { get; set; }
    
        public virtual HocPhiTheoDangKy HocPhiTheoDangKy { get; set; }
        public virtual NienKhoaHocKy NienKhoaHocKy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
