//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.LopTinChis = new HashSet<LopTinChi>();
        }

        [Required(ErrorMessage = "Mã giảng viên không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã giảng viên")]
        public string MaGV { get; set; }

        [Required(ErrorMessage = "Họ và tên lót không được trống", AllowEmptyStrings = false)]
        [StringLength(150)]
        [Display(Name = "Họ và tên lót")]
        public string HoVaTenLot { get; set; }

        [Required(ErrorMessage = "Tên giảng viên không được trống", AllowEmptyStrings = false)]
        [StringLength(50)]
        [Display(Name = "Tên giảng viên")]
        public string TenGV { get; set; }

        [Required(ErrorMessage = "Ngày sinh không được trống")]
        [Display(Name = "Ngày sinh")]
        public System.DateTime NgaySinh { get; set; }

        [Required(ErrorMessage = "Giới tính không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Trình độ không được trống", AllowEmptyStrings = false)]
        [StringLength(150)]
        [Display(Name = "Trình độ")]
        public string TrinhDo { get; set; }

        [Required(ErrorMessage = "Số điện thoại không được trống", AllowEmptyStrings = false)]
        [StringLength(50)]
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }

        [Required(ErrorMessage = "Email không được trống", AllowEmptyStrings = false)]
        [StringLength(150)]
        [Display(Name = "Email")]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$", ErrorMessage = "Please provide valid email id")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Mã khoa không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã khoa")]
        public string MaKhoa { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được trống", AllowEmptyStrings = false)]
        [StringLength(4000)]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopTinChi> LopTinChis { get; set; }
    }
}
