//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiaTinChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaTinChi()
        {
            this.HocPhiTheoDangKies = new HashSet<HocPhiTheoDangKy>();
        }

        [Required(ErrorMessage = "Mã giá tín chỉ không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã giá tín chỉ")]
        public string MaGiaTC { get; set; }

        [Required(ErrorMessage = "Mã hệ đào tạo không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã hệ đào tạo")]
        public string MaHDT { get; set; }

        [Required(ErrorMessage = "Giá không được trống")]
        [Display(Name = "Giá")]
        public double Gia { get; set; }

        [Required(ErrorMessage = "Ngày thay đổi không được trống")]
        [Display(Name = "Ngày thay đổi")]
        public System.DateTime NgayThayDoi { get; set; }
    
        public virtual HeDaoTao HeDaoTao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocPhiTheoDangKy> HocPhiTheoDangKies { get; set; }
    }
}
