//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTinChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaTinChi()
        {
            this.HocPhiTheoDangKies = new HashSet<HocPhiTheoDangKy>();
        }
    
        public string MaGiaTC { get; set; }
        public string MaHDT { get; set; }
        public double Gia { get; set; }
        public System.DateTime NgayThayDoi { get; set; }
        public string NienKhoa { get; set; }
    
        public virtual HeDaoTao HeDaoTao { get; set; }
        public virtual NienKhoaHocKy NienKhoaHocKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocPhiTheoDangKy> HocPhiTheoDangKies { get; set; }
    }
}
