//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HeDaoTao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeDaoTao()
        {
            this.GiaTinChis = new HashSet<GiaTinChi>();
            this.SinhViens = new HashSet<SinhVien>();
        }

        [Required(ErrorMessage = "Mã hệ đào tạo không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã hệ đào tạo")]
        public string MaHDT { get; set; }

        [Required(ErrorMessage = "Tên hệ đào tạo không được trống", AllowEmptyStrings = false)]
        [StringLength(150)]
        [Display(Name = "Tên hệ đào tạo")]
        public string TenHDT { get; set; }

        [StringLength(4000)]
        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaTinChi> GiaTinChis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
