//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhiTheoDangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocPhiTheoDangKy()
        {
            this.DongHocPhis = new HashSet<DongHocPhi>();
        }
    
        public string ID { get; set; }
        public double SoTienDong { get; set; }
        public int SoTinChi { get; set; }
        public string NienKhoa { get; set; }
        public string GhiChu { get; set; }
        public string MaGiaTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DongHocPhi> DongHocPhis { get; set; }
        public virtual GiaTinChi GiaTinChi { get; set; }
    }
}
