//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HocPhiTheoDangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocPhiTheoDangKy()
        {
            this.DongHocPhis = new HashSet<DongHocPhi>();
        }

        [Required(ErrorMessage = "ID không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "ID Học phí")]
        public string ID { get; set; }

        [Required(ErrorMessage = "Số tiền đóng không được trống")]
        [Display(Name = "Số tiền đóng")]
        public double SoTienDong { get; set; }

        [Required(ErrorMessage = "Số tín chỉ không được trống")]
        [Display(Name = "Số tín chỉ")]
        public int SoTinChi { get; set; }

        [Required(ErrorMessage = "Niên khóa không được trống", AllowEmptyStrings = false)]
        [StringLength(50)]
        [Display(Name = "Niên khóa")]
        public string NienKhoa { get; set; }

        [StringLength(4000)]
        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        [Required(ErrorMessage = "Mã giá tín chỉ không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã giá tín chỉ")]
        public string MaGiaTC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DongHocPhi> DongHocPhis { get; set; }
        public virtual GiaTinChi GiaTinChi { get; set; }
    }
}
