//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LopTinChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopTinChi()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
            this.ThoiKhoaBieux = new HashSet<ThoiKhoaBieu>();
            this.SinhViens = new HashSet<SinhVien>();
        }
        [Display(Name = "Mã lớp tín chỉ")]
        public int MaLopTC { get; set; }

        [Required(ErrorMessage = "Học kỳ không được trống")]    
        [Display(Name = "Mã lớp")]
        public short HocKy { get; set; }

        [Required(ErrorMessage = "Nhóm không được trống")]
        [Display(Name = "Nhóm")]
        public short Nhom { get; set; }

        [Required(ErrorMessage = "Niên khóa không được trống", AllowEmptyStrings = false)]
        [StringLength(50)]
        [Display(Name = "Niên khóa")]
        public string NienKhoa { get; set; }

        [Required(ErrorMessage = "Mã môn học không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã môn học")]
        public string MaMonHoc { get; set; }

        [Required(ErrorMessage = "Mã giảng viên không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã giảng viên")]
        public string MaGV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieux { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
