//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.LopTinChis = new HashSet<LopTinChi>();
        }
        [Display(Name = "Mã môn học")]
        public string MaMH { get; set; }
        [Display(Name = "Tên môn học")]
        public string TenMH { get; set; }
        [Display(Name = "Số tín chỉ lý thuyết")]
        public short SoTinChiLyThuyet { get; set; }
        [Display(Name = "Số tín chỉ thực hành")]
        public short SoTinChiThucHanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopTinChi> LopTinChis { get; set; }
    }
}
