//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonHocDangKy
    {
        [Required(ErrorMessage = "Mã lớp tín chỉ không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã lớp tín chỉ")]
        public string MaLopTC { get; set; }

        [Required(ErrorMessage = "Mã môn học không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã môn học")]
        public string MaMH { get; set; }
    }
}
