//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.DiemDanhs = new HashSet<DiemDanh>();
            this.DongHocPhis = new HashSet<DongHocPhi>();
            this.LopTinChis = new HashSet<LopTinChi>();
        }

        [Required(ErrorMessage = "Mã sinh viên không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã sinh viên")]
        public string MaSV { get; set; }

        [Required(ErrorMessage = "Họ và tên lót không được trống", AllowEmptyStrings = false)]
        [StringLength(150)]
        [Display(Name = "Họ và tên lót")]
        public string HoVaTenLot { get; set; }

        [Required(ErrorMessage = "Tên sinh viên không được trống", AllowEmptyStrings = false)]
        [StringLength(50)]
        [Display(Name = "Tên sinh viên")]
        public string TenSV { get; set; }

        [Required(ErrorMessage = "Giới tính không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Giới tính")]
        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Ngày sinh không được trống")]
        [Display(Name = "Ngày sinh")]
        public System.DateTime NgaySinh { get; set; }

        [Required(ErrorMessage = "Hệ đào tạo không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Hệ đào tạo")]
        public string HeDaoTao { get; set; }

        [Required(ErrorMessage = "Email không được trống", AllowEmptyStrings = false)]
        [StringLength(150)]
        [Display(Name = "Email")]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",ErrorMessage = "Please provide valid email id")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Mã lớp không được trống", AllowEmptyStrings = false)]
        [StringLength(10)]
        [Display(Name = "Mã lớp")]
        public string MaLop { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được trống", AllowEmptyStrings = false)]
        [StringLength(4000)]
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DongHocPhi> DongHocPhis { get; set; }
        public virtual HeDaoTao HeDaoTao1 { get; set; }
        public virtual Lop Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopTinChi> LopTinChis { get; set; }
    }
}
