//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public System.DateTime Ngay { get; set; }
        public string Buoi { get; set; }
        public short TietBD { get; set; }
        public int MaLopTC { get; set; }
    
        public virtual LopTinChi LopTinChi { get; set; }
    }
}
