//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThoiKhoaBieu
    {
        [Display(Name = "Ngày")]
        public System.DateTime Ngay { get; set; }
        [Display(Name = "Buổi")]
        public string Buoi { get; set; }
        [Display(Name = "Tiết bắt đầu")]
        public short TietBD { get; set; }
        [Display(Name = "Mã lớp tín chỉ")]
        public int MaLopTC { get; set; }
    
        public virtual LopTinChi LopTinChi { get; set; }
    }
}
